#spring
spring:
  profiles:
    active: local #??? ????????
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      maxFileSize: 10MB
      maxRequestSize: 20MB
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

#server
server:
  port: 8888

#mybatis
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false

#log
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: DEBUG
    javax.activation: ERROR
    _org: ERROR
    sun: ERROR
    org.apache: ERROR
    org.springframework.beans: ERROR
    org.springframework.boot: ERROR
    org.springframework.core: ERROR
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.servlet.handler: INFO
    org.mybatis.spring.SqlSessionFactoryBean: ERROR
    org.thymeleaf: ERROR
    com.zaxxer: ERROR

#--- ?? ??! (??? ????!!!!!!!)

---
#??
spring:
  config.activate.on-profile: local #?? ?? ????? ?? ?
  datasource:
    url: jdbc:mysql://3.35.221.139:3306/m_cms?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: casanova1!@
resources:
  location: /C:/Users/musign design lab/Documents/workspace-sts-3.9.6.RELEASE/m_cms/files/
  uri_path: /files
---
#??
spring:
  config.activate.on-profile: server
  datasource:
    url: jdbc:mysql://3.35.221.139:3306/m_cms?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: casanova1!@
resources:
  location: /var/www/html/m_cms/files/
  uri_path: /files